name: Decommissioning resources...

on: {                                                                   #only manual running
    workflow_dispatch: {} 
}

permissions: {                                                          #minimum permissions
    id-token: write,                                                    #for OIDC login (without saving keys)
    contents: read                                                      #to read repo
}

jobs:
  destroy:
    runs-on: ubuntu-latest                                              #Linux VM
    defaults: { 
        run: { 
            working-directory: terraform                                #every run command will be done in "terraform/" (where we have .tf files)
        } 
    }
    
    steps:
      - uses: actions/checkout@v4                                       #checkout repo on runner
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: hashicorp/setup-terraform@v3                              #installing terraform CLI
      - run: terraform init -input=false -reconfigure                   #initializing a Terraform working dir
      - run: terraform destroy -input=false -auto-approve -lock-timeout=5m -var="ssh_public_key_value=${{ secrets.SSH_PUBLIC_KEY }}"  #delete all resources (VM, disk, IP, network, NSG,...)
